// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_record_small2.proto

package edu.buffalo.cse.ubwins.cellmon;

public final class DataRecordSmall2 {
  private DataRecordSmall2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface DataEntriesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataEntries)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Timestamp 
     * </pre>
     *
     * <code>optional uint64 TIMESTAMP = 1;</code>
     */
    long getTIMESTAMP();

    /**
     * <pre>
     * Location 
     * </pre>
     *
     * <code>optional double FUSED_LAT = 2;</code>
     */
    double getFUSEDLAT();

    /**
     * <code>optional double FUSED_LONG = 3;</code>
     */
    double getFUSEDLONG();

    /**
     * <code>optional .DataEntries.NetType NETWORK_TYPE = 4;</code>
     */
    int getNETWORKTYPEValue();
    /**
     * <code>optional .DataEntries.NetType NETWORK_TYPE = 4;</code>
     */
    edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.NetType getNETWORKTYPE();

    /**
     * <code>optional .DataEntries.CellType NETWORK_CELL_TYPE = 5;</code>
     */
    int getNETWORKCELLTYPEValue();
    /**
     * <code>optional .DataEntries.CellType NETWORK_CELL_TYPE = 5;</code>
     */
    edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.CellType getNETWORKCELLTYPE();

    /**
     * <code>optional sint32 SIGNAL_DBM = 6;</code>
     */
    int getSIGNALDBM();
  }
  /**
   * Protobuf type {@code DataEntries}
   */
  public  static final class DataEntries extends
      com.google.protobuf.GeneratedMessageLite<
          DataEntries, DataEntries.Builder> implements
      // @@protoc_insertion_point(message_implements:DataEntries)
      DataEntriesOrBuilder {
    private DataEntries() {
    }
    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html 
     * </pre>
     *
     * Protobuf enum {@code DataEntries.NetType}
     */
    public enum NetType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>NETWORK_TYPE_UNKNOWN = 0;</code>
       */
      NETWORK_TYPE_UNKNOWN(0),
      /**
       * <code>NETWORK_TYPE_GPRS = 1;</code>
       */
      NETWORK_TYPE_GPRS(1),
      /**
       * <code>NETWORK_TYPE_EDGE = 2;</code>
       */
      NETWORK_TYPE_EDGE(2),
      /**
       * <code>NETWORK_TYPE_UMTS = 3;</code>
       */
      NETWORK_TYPE_UMTS(3),
      /**
       * <code>NETWORK_TYPE_HSDPA = 4;</code>
       */
      NETWORK_TYPE_HSDPA(4),
      /**
       * <code>NETWORK_TYPE_HSUPA = 5;</code>
       */
      NETWORK_TYPE_HSUPA(5),
      /**
       * <code>NETWORK_TYPE_HSPA = 6;</code>
       */
      NETWORK_TYPE_HSPA(6),
      /**
       * <code>NETWORK_TYPE_CDMA = 7;</code>
       */
      NETWORK_TYPE_CDMA(7),
      /**
       * <code>NETWORK_TYPE_EVDO_0 = 8;</code>
       */
      NETWORK_TYPE_EVDO_0(8),
      /**
       * <code>NETWORK_TYPE_EVDO_A = 9;</code>
       */
      NETWORK_TYPE_EVDO_A(9),
      /**
       * <code>NETWORK_TYPE_EVDO_B = 10;</code>
       */
      NETWORK_TYPE_EVDO_B(10),
      /**
       * <code>NETWORK_TYPE_1xRTT = 11;</code>
       */
      NETWORK_TYPE_1xRTT(11),
      /**
       * <code>NETWORK_TYPE_IDEN = 12;</code>
       */
      NETWORK_TYPE_IDEN(12),
      /**
       * <code>NETWORK_TYPE_LTE = 13;</code>
       */
      NETWORK_TYPE_LTE(13),
      /**
       * <code>NETWORK_TYPE_EHRPD = 14;</code>
       */
      NETWORK_TYPE_EHRPD(14),
      /**
       * <code>NETWORK_TYPE_HSPAP = 15;</code>
       */
      NETWORK_TYPE_HSPAP(15),
      /**
       * <code>NETWORK_TYPE_GSM = 16;</code>
       */
      NETWORK_TYPE_GSM(16),
      /**
       * <code>NETWORK_TYPE_TD_SCDMA = 17;</code>
       */
      NETWORK_TYPE_TD_SCDMA(17),
      /**
       * <code>NETWORK_TYPE_IWLAN = 18;</code>
       */
      NETWORK_TYPE_IWLAN(18),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NETWORK_TYPE_UNKNOWN = 0;</code>
       */
      public static final int NETWORK_TYPE_UNKNOWN_VALUE = 0;
      /**
       * <code>NETWORK_TYPE_GPRS = 1;</code>
       */
      public static final int NETWORK_TYPE_GPRS_VALUE = 1;
      /**
       * <code>NETWORK_TYPE_EDGE = 2;</code>
       */
      public static final int NETWORK_TYPE_EDGE_VALUE = 2;
      /**
       * <code>NETWORK_TYPE_UMTS = 3;</code>
       */
      public static final int NETWORK_TYPE_UMTS_VALUE = 3;
      /**
       * <code>NETWORK_TYPE_HSDPA = 4;</code>
       */
      public static final int NETWORK_TYPE_HSDPA_VALUE = 4;
      /**
       * <code>NETWORK_TYPE_HSUPA = 5;</code>
       */
      public static final int NETWORK_TYPE_HSUPA_VALUE = 5;
      /**
       * <code>NETWORK_TYPE_HSPA = 6;</code>
       */
      public static final int NETWORK_TYPE_HSPA_VALUE = 6;
      /**
       * <code>NETWORK_TYPE_CDMA = 7;</code>
       */
      public static final int NETWORK_TYPE_CDMA_VALUE = 7;
      /**
       * <code>NETWORK_TYPE_EVDO_0 = 8;</code>
       */
      public static final int NETWORK_TYPE_EVDO_0_VALUE = 8;
      /**
       * <code>NETWORK_TYPE_EVDO_A = 9;</code>
       */
      public static final int NETWORK_TYPE_EVDO_A_VALUE = 9;
      /**
       * <code>NETWORK_TYPE_EVDO_B = 10;</code>
       */
      public static final int NETWORK_TYPE_EVDO_B_VALUE = 10;
      /**
       * <code>NETWORK_TYPE_1xRTT = 11;</code>
       */
      public static final int NETWORK_TYPE_1xRTT_VALUE = 11;
      /**
       * <code>NETWORK_TYPE_IDEN = 12;</code>
       */
      public static final int NETWORK_TYPE_IDEN_VALUE = 12;
      /**
       * <code>NETWORK_TYPE_LTE = 13;</code>
       */
      public static final int NETWORK_TYPE_LTE_VALUE = 13;
      /**
       * <code>NETWORK_TYPE_EHRPD = 14;</code>
       */
      public static final int NETWORK_TYPE_EHRPD_VALUE = 14;
      /**
       * <code>NETWORK_TYPE_HSPAP = 15;</code>
       */
      public static final int NETWORK_TYPE_HSPAP_VALUE = 15;
      /**
       * <code>NETWORK_TYPE_GSM = 16;</code>
       */
      public static final int NETWORK_TYPE_GSM_VALUE = 16;
      /**
       * <code>NETWORK_TYPE_TD_SCDMA = 17;</code>
       */
      public static final int NETWORK_TYPE_TD_SCDMA_VALUE = 17;
      /**
       * <code>NETWORK_TYPE_IWLAN = 18;</code>
       */
      public static final int NETWORK_TYPE_IWLAN_VALUE = 18;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NetType valueOf(int value) {
        return forNumber(value);
      }

      public static NetType forNumber(int value) {
        switch (value) {
          case 0: return NETWORK_TYPE_UNKNOWN;
          case 1: return NETWORK_TYPE_GPRS;
          case 2: return NETWORK_TYPE_EDGE;
          case 3: return NETWORK_TYPE_UMTS;
          case 4: return NETWORK_TYPE_HSDPA;
          case 5: return NETWORK_TYPE_HSUPA;
          case 6: return NETWORK_TYPE_HSPA;
          case 7: return NETWORK_TYPE_CDMA;
          case 8: return NETWORK_TYPE_EVDO_0;
          case 9: return NETWORK_TYPE_EVDO_A;
          case 10: return NETWORK_TYPE_EVDO_B;
          case 11: return NETWORK_TYPE_1xRTT;
          case 12: return NETWORK_TYPE_IDEN;
          case 13: return NETWORK_TYPE_LTE;
          case 14: return NETWORK_TYPE_EHRPD;
          case 15: return NETWORK_TYPE_HSPAP;
          case 16: return NETWORK_TYPE_GSM;
          case 17: return NETWORK_TYPE_TD_SCDMA;
          case 18: return NETWORK_TYPE_IWLAN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NetType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NetType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NetType>() {
              public NetType findValueByNumber(int number) {
                return NetType.forNumber(number);
              }
            };

      private final int value;

      private NetType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DataEntries.NetType)
    }

    /**
     * <pre>
     * https://developer.android.com/reference/android/telephony/TelephonyManager.html#getAllCellInfo() 
     * </pre>
     *
     * Protobuf enum {@code DataEntries.CellType}
     */
    public enum CellType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>GSM = 0;</code>
       */
      GSM(0),
      /**
       * <code>CDMA = 1;</code>
       */
      CDMA(1),
      /**
       * <code>WCDMA = 2;</code>
       */
      WCDMA(2),
      /**
       * <code>LTE = 3;</code>
       */
      LTE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>GSM = 0;</code>
       */
      public static final int GSM_VALUE = 0;
      /**
       * <code>CDMA = 1;</code>
       */
      public static final int CDMA_VALUE = 1;
      /**
       * <code>WCDMA = 2;</code>
       */
      public static final int WCDMA_VALUE = 2;
      /**
       * <code>LTE = 3;</code>
       */
      public static final int LTE_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CellType valueOf(int value) {
        return forNumber(value);
      }

      public static CellType forNumber(int value) {
        switch (value) {
          case 0: return GSM;
          case 1: return CDMA;
          case 2: return WCDMA;
          case 3: return LTE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CellType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CellType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CellType>() {
              public CellType findValueByNumber(int number) {
                return CellType.forNumber(number);
              }
            };

      private final int value;

      private CellType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DataEntries.CellType)
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long tIMESTAMP_;
    /**
     * <pre>
     * Timestamp 
     * </pre>
     *
     * <code>optional uint64 TIMESTAMP = 1;</code>
     */
    public long getTIMESTAMP() {
      return tIMESTAMP_;
    }
    /**
     * <pre>
     * Timestamp 
     * </pre>
     *
     * <code>optional uint64 TIMESTAMP = 1;</code>
     */
    private void setTIMESTAMP(long value) {
      
      tIMESTAMP_ = value;
    }
    /**
     * <pre>
     * Timestamp 
     * </pre>
     *
     * <code>optional uint64 TIMESTAMP = 1;</code>
     */
    private void clearTIMESTAMP() {
      
      tIMESTAMP_ = 0L;
    }

    public static final int FUSED_LAT_FIELD_NUMBER = 2;
    private double fUSEDLAT_;
    /**
     * <pre>
     * Location 
     * </pre>
     *
     * <code>optional double FUSED_LAT = 2;</code>
     */
    public double getFUSEDLAT() {
      return fUSEDLAT_;
    }
    /**
     * <pre>
     * Location 
     * </pre>
     *
     * <code>optional double FUSED_LAT = 2;</code>
     */
    private void setFUSEDLAT(double value) {
      
      fUSEDLAT_ = value;
    }
    /**
     * <pre>
     * Location 
     * </pre>
     *
     * <code>optional double FUSED_LAT = 2;</code>
     */
    private void clearFUSEDLAT() {
      
      fUSEDLAT_ = 0D;
    }

    public static final int FUSED_LONG_FIELD_NUMBER = 3;
    private double fUSEDLONG_;
    /**
     * <code>optional double FUSED_LONG = 3;</code>
     */
    public double getFUSEDLONG() {
      return fUSEDLONG_;
    }
    /**
     * <code>optional double FUSED_LONG = 3;</code>
     */
    private void setFUSEDLONG(double value) {
      
      fUSEDLONG_ = value;
    }
    /**
     * <code>optional double FUSED_LONG = 3;</code>
     */
    private void clearFUSEDLONG() {
      
      fUSEDLONG_ = 0D;
    }

    public static final int NETWORK_TYPE_FIELD_NUMBER = 4;
    private int nETWORKTYPE_;
    /**
     * <code>optional .DataEntries.NetType NETWORK_TYPE = 4;</code>
     */
    public int getNETWORKTYPEValue() {
      return nETWORKTYPE_;
    }
    /**
     * <code>optional .DataEntries.NetType NETWORK_TYPE = 4;</code>
     */
    public edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.NetType getNETWORKTYPE() {
      edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.NetType result = edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.NetType.forNumber(nETWORKTYPE_);
      return result == null ? edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.NetType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .DataEntries.NetType NETWORK_TYPE = 4;</code>
     */
    private void setNETWORKTYPEValue(int value) {
        nETWORKTYPE_ = value;
    }
    /**
     * <code>optional .DataEntries.NetType NETWORK_TYPE = 4;</code>
     */
    private void setNETWORKTYPE(edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.NetType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      nETWORKTYPE_ = value.getNumber();
    }
    /**
     * <code>optional .DataEntries.NetType NETWORK_TYPE = 4;</code>
     */
    private void clearNETWORKTYPE() {
      
      nETWORKTYPE_ = 0;
    }

    public static final int NETWORK_CELL_TYPE_FIELD_NUMBER = 5;
    private int nETWORKCELLTYPE_;
    /**
     * <code>optional .DataEntries.CellType NETWORK_CELL_TYPE = 5;</code>
     */
    public int getNETWORKCELLTYPEValue() {
      return nETWORKCELLTYPE_;
    }
    /**
     * <code>optional .DataEntries.CellType NETWORK_CELL_TYPE = 5;</code>
     */
    public edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.CellType getNETWORKCELLTYPE() {
      edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.CellType result = edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.CellType.forNumber(nETWORKCELLTYPE_);
      return result == null ? edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.CellType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .DataEntries.CellType NETWORK_CELL_TYPE = 5;</code>
     */
    private void setNETWORKCELLTYPEValue(int value) {
        nETWORKCELLTYPE_ = value;
    }
    /**
     * <code>optional .DataEntries.CellType NETWORK_CELL_TYPE = 5;</code>
     */
    private void setNETWORKCELLTYPE(edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.CellType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      nETWORKCELLTYPE_ = value.getNumber();
    }
    /**
     * <code>optional .DataEntries.CellType NETWORK_CELL_TYPE = 5;</code>
     */
    private void clearNETWORKCELLTYPE() {
      
      nETWORKCELLTYPE_ = 0;
    }

    public static final int SIGNAL_DBM_FIELD_NUMBER = 6;
    private int sIGNALDBM_;
    /**
     * <code>optional sint32 SIGNAL_DBM = 6;</code>
     */
    public int getSIGNALDBM() {
      return sIGNALDBM_;
    }
    /**
     * <code>optional sint32 SIGNAL_DBM = 6;</code>
     */
    private void setSIGNALDBM(int value) {
      
      sIGNALDBM_ = value;
    }
    /**
     * <code>optional sint32 SIGNAL_DBM = 6;</code>
     */
    private void clearSIGNALDBM() {
      
      sIGNALDBM_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tIMESTAMP_ != 0L) {
        output.writeUInt64(1, tIMESTAMP_);
      }
      if (fUSEDLAT_ != 0D) {
        output.writeDouble(2, fUSEDLAT_);
      }
      if (fUSEDLONG_ != 0D) {
        output.writeDouble(3, fUSEDLONG_);
      }
      if (nETWORKTYPE_ != edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.NetType.NETWORK_TYPE_UNKNOWN.getNumber()) {
        output.writeEnum(4, nETWORKTYPE_);
      }
      if (nETWORKCELLTYPE_ != edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.CellType.GSM.getNumber()) {
        output.writeEnum(5, nETWORKCELLTYPE_);
      }
      if (sIGNALDBM_ != 0) {
        output.writeSInt32(6, sIGNALDBM_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (tIMESTAMP_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, tIMESTAMP_);
      }
      if (fUSEDLAT_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, fUSEDLAT_);
      }
      if (fUSEDLONG_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, fUSEDLONG_);
      }
      if (nETWORKTYPE_ != edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.NetType.NETWORK_TYPE_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, nETWORKTYPE_);
      }
      if (nETWORKCELLTYPE_ != edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.CellType.GSM.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, nETWORKCELLTYPE_);
      }
      if (sIGNALDBM_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(6, sIGNALDBM_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code DataEntries}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries, Builder> implements
        // @@protoc_insertion_point(builder_implements:DataEntries)
        edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntriesOrBuilder {
      // Construct using edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Timestamp 
       * </pre>
       *
       * <code>optional uint64 TIMESTAMP = 1;</code>
       */
      public long getTIMESTAMP() {
        return instance.getTIMESTAMP();
      }
      /**
       * <pre>
       * Timestamp 
       * </pre>
       *
       * <code>optional uint64 TIMESTAMP = 1;</code>
       */
      public Builder setTIMESTAMP(long value) {
        copyOnWrite();
        instance.setTIMESTAMP(value);
        return this;
      }
      /**
       * <pre>
       * Timestamp 
       * </pre>
       *
       * <code>optional uint64 TIMESTAMP = 1;</code>
       */
      public Builder clearTIMESTAMP() {
        copyOnWrite();
        instance.clearTIMESTAMP();
        return this;
      }

      /**
       * <pre>
       * Location 
       * </pre>
       *
       * <code>optional double FUSED_LAT = 2;</code>
       */
      public double getFUSEDLAT() {
        return instance.getFUSEDLAT();
      }
      /**
       * <pre>
       * Location 
       * </pre>
       *
       * <code>optional double FUSED_LAT = 2;</code>
       */
      public Builder setFUSEDLAT(double value) {
        copyOnWrite();
        instance.setFUSEDLAT(value);
        return this;
      }
      /**
       * <pre>
       * Location 
       * </pre>
       *
       * <code>optional double FUSED_LAT = 2;</code>
       */
      public Builder clearFUSEDLAT() {
        copyOnWrite();
        instance.clearFUSEDLAT();
        return this;
      }

      /**
       * <code>optional double FUSED_LONG = 3;</code>
       */
      public double getFUSEDLONG() {
        return instance.getFUSEDLONG();
      }
      /**
       * <code>optional double FUSED_LONG = 3;</code>
       */
      public Builder setFUSEDLONG(double value) {
        copyOnWrite();
        instance.setFUSEDLONG(value);
        return this;
      }
      /**
       * <code>optional double FUSED_LONG = 3;</code>
       */
      public Builder clearFUSEDLONG() {
        copyOnWrite();
        instance.clearFUSEDLONG();
        return this;
      }

      /**
       * <code>optional .DataEntries.NetType NETWORK_TYPE = 4;</code>
       */
      public int getNETWORKTYPEValue() {
        return instance.getNETWORKTYPEValue();
      }
      /**
       * <code>optional .DataEntries.NetType NETWORK_TYPE = 4;</code>
       */
      public Builder setNETWORKTYPEValue(int value) {
        copyOnWrite();
        instance.setNETWORKTYPEValue(value);
        return this;
      }
      /**
       * <code>optional .DataEntries.NetType NETWORK_TYPE = 4;</code>
       */
      public edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.NetType getNETWORKTYPE() {
        return instance.getNETWORKTYPE();
      }
      /**
       * <code>optional .DataEntries.NetType NETWORK_TYPE = 4;</code>
       */
      public Builder setNETWORKTYPE(edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.NetType value) {
        copyOnWrite();
        instance.setNETWORKTYPE(value);
        return this;
      }
      /**
       * <code>optional .DataEntries.NetType NETWORK_TYPE = 4;</code>
       */
      public Builder clearNETWORKTYPE() {
        copyOnWrite();
        instance.clearNETWORKTYPE();
        return this;
      }

      /**
       * <code>optional .DataEntries.CellType NETWORK_CELL_TYPE = 5;</code>
       */
      public int getNETWORKCELLTYPEValue() {
        return instance.getNETWORKCELLTYPEValue();
      }
      /**
       * <code>optional .DataEntries.CellType NETWORK_CELL_TYPE = 5;</code>
       */
      public Builder setNETWORKCELLTYPEValue(int value) {
        copyOnWrite();
        instance.setNETWORKCELLTYPEValue(value);
        return this;
      }
      /**
       * <code>optional .DataEntries.CellType NETWORK_CELL_TYPE = 5;</code>
       */
      public edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.CellType getNETWORKCELLTYPE() {
        return instance.getNETWORKCELLTYPE();
      }
      /**
       * <code>optional .DataEntries.CellType NETWORK_CELL_TYPE = 5;</code>
       */
      public Builder setNETWORKCELLTYPE(edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.CellType value) {
        copyOnWrite();
        instance.setNETWORKCELLTYPE(value);
        return this;
      }
      /**
       * <code>optional .DataEntries.CellType NETWORK_CELL_TYPE = 5;</code>
       */
      public Builder clearNETWORKCELLTYPE() {
        copyOnWrite();
        instance.clearNETWORKCELLTYPE();
        return this;
      }

      /**
       * <code>optional sint32 SIGNAL_DBM = 6;</code>
       */
      public int getSIGNALDBM() {
        return instance.getSIGNALDBM();
      }
      /**
       * <code>optional sint32 SIGNAL_DBM = 6;</code>
       */
      public Builder setSIGNALDBM(int value) {
        copyOnWrite();
        instance.setSIGNALDBM(value);
        return this;
      }
      /**
       * <code>optional sint32 SIGNAL_DBM = 6;</code>
       */
      public Builder clearSIGNALDBM() {
        copyOnWrite();
        instance.clearSIGNALDBM();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DataEntries)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries other = (edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries) arg1;
          tIMESTAMP_ = visitor.visitLong(tIMESTAMP_ != 0L, tIMESTAMP_,
              other.tIMESTAMP_ != 0L, other.tIMESTAMP_);
          fUSEDLAT_ = visitor.visitDouble(fUSEDLAT_ != 0D, fUSEDLAT_,
              other.fUSEDLAT_ != 0D, other.fUSEDLAT_);
          fUSEDLONG_ = visitor.visitDouble(fUSEDLONG_ != 0D, fUSEDLONG_,
              other.fUSEDLONG_ != 0D, other.fUSEDLONG_);
          nETWORKTYPE_ = visitor.visitInt(nETWORKTYPE_ != 0, nETWORKTYPE_,    other.nETWORKTYPE_ != 0, other.nETWORKTYPE_);
          nETWORKCELLTYPE_ = visitor.visitInt(nETWORKCELLTYPE_ != 0, nETWORKCELLTYPE_,    other.nETWORKCELLTYPE_ != 0, other.nETWORKCELLTYPE_);
          sIGNALDBM_ = visitor.visitInt(sIGNALDBM_ != 0, sIGNALDBM_,
              other.sIGNALDBM_ != 0, other.sIGNALDBM_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  tIMESTAMP_ = input.readUInt64();
                  break;
                }
                case 17: {

                  fUSEDLAT_ = input.readDouble();
                  break;
                }
                case 25: {

                  fUSEDLONG_ = input.readDouble();
                  break;
                }
                case 32: {
                  int rawValue = input.readEnum();

                  nETWORKTYPE_ = rawValue;
                  break;
                }
                case 40: {
                  int rawValue = input.readEnum();

                  nETWORKCELLTYPE_ = rawValue;
                  break;
                }
                case 48: {

                  sIGNALDBM_ = input.readSInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:DataEntries)
    private static final edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataEntries();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<DataEntries> PARSER;

    public static com.google.protobuf.Parser<DataEntries> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DataRecords2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataRecords2)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    java.lang.String getIMEIHASH();
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    com.google.protobuf.ByteString
        getIMEIHASHBytes();

    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    java.util.List<edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries> 
        getENTRYList();
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries getENTRY(int index);
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    int getENTRYCount();
  }
  /**
   * Protobuf type {@code DataRecords2}
   */
  public  static final class DataRecords2 extends
      com.google.protobuf.GeneratedMessageLite<
          DataRecords2, DataRecords2.Builder> implements
      // @@protoc_insertion_point(message_implements:DataRecords2)
      DataRecords2OrBuilder {
    private DataRecords2() {
      iMEIHASH_ = "";
      eNTRY_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int IMEI_HASH_FIELD_NUMBER = 1;
    private java.lang.String iMEIHASH_;
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    public java.lang.String getIMEIHASH() {
      return iMEIHASH_;
    }
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIMEIHASHBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(iMEIHASH_);
    }
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    private void setIMEIHASH(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iMEIHASH_ = value;
    }
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    private void clearIMEIHASH() {
      
      iMEIHASH_ = getDefaultInstance().getIMEIHASH();
    }
    /**
     * <code>optional string IMEI_HASH = 1;</code>
     */
    private void setIMEIHASHBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iMEIHASH_ = value.toStringUtf8();
    }

    public static final int ENTRY_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries> eNTRY_;
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    public java.util.List<edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries> getENTRYList() {
      return eNTRY_;
    }
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    public java.util.List<? extends edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntriesOrBuilder> 
        getENTRYOrBuilderList() {
      return eNTRY_;
    }
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    public int getENTRYCount() {
      return eNTRY_.size();
    }
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    public edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries getENTRY(int index) {
      return eNTRY_.get(index);
    }
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    public edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntriesOrBuilder getENTRYOrBuilder(
        int index) {
      return eNTRY_.get(index);
    }
    private void ensureENTRYIsMutable() {
      if (!eNTRY_.isModifiable()) {
        eNTRY_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(eNTRY_);
       }
    }

    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    private void setENTRY(
        int index, edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureENTRYIsMutable();
      eNTRY_.set(index, value);
    }
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    private void setENTRY(
        int index, edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.Builder builderForValue) {
      ensureENTRYIsMutable();
      eNTRY_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    private void addENTRY(edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureENTRYIsMutable();
      eNTRY_.add(value);
    }
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    private void addENTRY(
        int index, edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureENTRYIsMutable();
      eNTRY_.add(index, value);
    }
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    private void addENTRY(
        edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.Builder builderForValue) {
      ensureENTRYIsMutable();
      eNTRY_.add(builderForValue.build());
    }
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    private void addENTRY(
        int index, edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.Builder builderForValue) {
      ensureENTRYIsMutable();
      eNTRY_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    private void addAllENTRY(
        java.lang.Iterable<? extends edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries> values) {
      ensureENTRYIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, eNTRY_);
    }
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    private void clearENTRY() {
      eNTRY_ = emptyProtobufList();
    }
    /**
     * <code>repeated .DataEntries ENTRY = 2;</code>
     */
    private void removeENTRY(int index) {
      ensureENTRYIsMutable();
      eNTRY_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!iMEIHASH_.isEmpty()) {
        output.writeString(1, getIMEIHASH());
      }
      for (int i = 0; i < eNTRY_.size(); i++) {
        output.writeMessage(2, eNTRY_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!iMEIHASH_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getIMEIHASH());
      }
      for (int i = 0; i < eNTRY_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, eNTRY_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code DataRecords2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2, Builder> implements
        // @@protoc_insertion_point(builder_implements:DataRecords2)
        edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2OrBuilder {
      // Construct using edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public java.lang.String getIMEIHASH() {
        return instance.getIMEIHASH();
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIMEIHASHBytes() {
        return instance.getIMEIHASHBytes();
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public Builder setIMEIHASH(
          java.lang.String value) {
        copyOnWrite();
        instance.setIMEIHASH(value);
        return this;
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public Builder clearIMEIHASH() {
        copyOnWrite();
        instance.clearIMEIHASH();
        return this;
      }
      /**
       * <code>optional string IMEI_HASH = 1;</code>
       */
      public Builder setIMEIHASHBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIMEIHASHBytes(value);
        return this;
      }

      /**
       * <code>repeated .DataEntries ENTRY = 2;</code>
       */
      public java.util.List<edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries> getENTRYList() {
        return java.util.Collections.unmodifiableList(
            instance.getENTRYList());
      }
      /**
       * <code>repeated .DataEntries ENTRY = 2;</code>
       */
      public int getENTRYCount() {
        return instance.getENTRYCount();
      }/**
       * <code>repeated .DataEntries ENTRY = 2;</code>
       */
      public edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries getENTRY(int index) {
        return instance.getENTRY(index);
      }
      /**
       * <code>repeated .DataEntries ENTRY = 2;</code>
       */
      public Builder setENTRY(
          int index, edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries value) {
        copyOnWrite();
        instance.setENTRY(index, value);
        return this;
      }
      /**
       * <code>repeated .DataEntries ENTRY = 2;</code>
       */
      public Builder setENTRY(
          int index, edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.Builder builderForValue) {
        copyOnWrite();
        instance.setENTRY(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .DataEntries ENTRY = 2;</code>
       */
      public Builder addENTRY(edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries value) {
        copyOnWrite();
        instance.addENTRY(value);
        return this;
      }
      /**
       * <code>repeated .DataEntries ENTRY = 2;</code>
       */
      public Builder addENTRY(
          int index, edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries value) {
        copyOnWrite();
        instance.addENTRY(index, value);
        return this;
      }
      /**
       * <code>repeated .DataEntries ENTRY = 2;</code>
       */
      public Builder addENTRY(
          edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.Builder builderForValue) {
        copyOnWrite();
        instance.addENTRY(builderForValue);
        return this;
      }
      /**
       * <code>repeated .DataEntries ENTRY = 2;</code>
       */
      public Builder addENTRY(
          int index, edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.Builder builderForValue) {
        copyOnWrite();
        instance.addENTRY(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .DataEntries ENTRY = 2;</code>
       */
      public Builder addAllENTRY(
          java.lang.Iterable<? extends edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries> values) {
        copyOnWrite();
        instance.addAllENTRY(values);
        return this;
      }
      /**
       * <code>repeated .DataEntries ENTRY = 2;</code>
       */
      public Builder clearENTRY() {
        copyOnWrite();
        instance.clearENTRY();
        return this;
      }
      /**
       * <code>repeated .DataEntries ENTRY = 2;</code>
       */
      public Builder removeENTRY(int index) {
        copyOnWrite();
        instance.removeENTRY(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DataRecords2)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          eNTRY_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 other = (edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2) arg1;
          iMEIHASH_ = visitor.visitString(!iMEIHASH_.isEmpty(), iMEIHASH_,
              !other.iMEIHASH_.isEmpty(), other.iMEIHASH_);
          eNTRY_= visitor.visitList(eNTRY_, other.eNTRY_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  iMEIHASH_ = s;
                  break;
                }
                case 18: {
                  if (!eNTRY_.isModifiable()) {
                    eNTRY_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(eNTRY_);
                  }
                  eNTRY_.add(
                      input.readMessage(edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataEntries.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:DataRecords2)
    private static final edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataRecords2();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static edu.buffalo.cse.ubwins.cellmon.DataRecordSmall2.DataRecords2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<DataRecords2> PARSER;

    public static com.google.protobuf.Parser<DataRecords2> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
